//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharkAdministrativo.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Data;
    using SDKCONTPAQi;
    using System.Windows.Forms;
    
    public partial class AreaProduccion
    {
        public int id { get; set; }
        public string nombre { get; set; }

        /// <summary>
        /// Registra un objeto área de producción en la base de datos.
        /// </summary>
        /// <param name="area">El objeto a registrar.</param>
        public void registrar(AreaProduccion area)
        {
             try{ 
                 using(bdsharkEntities db = new bdsharkEntities())
                {
                    db.AreasProduccion.Add(area);
                    db.SaveChanges();
                 }
            }catch(Exception ex){
                MessageBox.Show("Error: "+ex+"\nError en la autenticación con la base de datos", "Aviso Shark" );
            }
        }

        /// <summary>
        /// Obtiene un objeto AreaProduccion específico.
        /// </summary>
        /// <param name="name">Parámetro de búsqueda</param>
        /// <returns>El área encontrada.</returns>
        public AreaProduccion obtener(string name)
        {
            AreaProduccion _area = new AreaProduccion();
             try{ 
                 using(bdsharkEntities db = new bdsharkEntities())
                {
                    db.Configuration.LazyLoadingEnabled = true;
                    var areaQuery = from area in db.AreasProduccion where area.nombre.Trim() == name select area;
                    // Iterate through the results of the parameterized query.
                    foreach (var area in areaQuery)
                    {
                        _area = area;
                    }
                 }
            }catch(Exception ex){
                MessageBox.Show("Error: "+ex+"\nError en la autenticación con la base de datos", "Aviso Shark" );
            }

            return _area;
        }

        /// <summary>
        /// Obtiene un área específica.
        /// </summary>
        /// <param name="id">Parámetro de búsqueda</param>
        /// <returns>El área encontrada.</returns>
        public AreaProduccion obtenerPorID(int id)
        {
            AreaProduccion area = new AreaProduccion();
             try{ 
                 using(bdsharkEntities db = new bdsharkEntities())
                {
                    area = db.AreasProduccion.Find(id);
                 }
             }
             catch (Exception ex)
             {
                 MessageBox.Show("Error: " + ex + "\nError en la autenticación con la base de datos", "Aviso Shark");
             }
            return area;
        }

        /// <summary>
        /// Obtiene todas las áreas de produccion creadas en shark.
        /// </summary>
        /// <returns></returns>
        public List<AreaProduccion> obtenerTodos()
        {
            List<AreaProduccion> areas = new List<AreaProduccion>();
             try{ 
                 using(bdsharkEntities db = new bdsharkEntities())
                 {
                    db.Configuration.LazyLoadingEnabled = true;
                    var areasQuery = from area in db.AreasProduccion select area;
                    // Iterate through the results of the parameterized query.
                    foreach (var area in areasQuery)
                    {
                        areas.Add(area);
                    }
                 }
            }catch(Exception ex){
                MessageBox.Show("Error: "+ex+"\nError en la autenticación con la base de datos", "Aviso Shark" );
            }
            return areas;
        }
    }
}
