//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharkAdministrativo.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdsharkEntities : DbContext
    {
        public bdsharkEntities()
            : base("name=bdsharkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Almacen> Almacenes { get; set; }
        public DbSet<AreaProduccion> AreasProduccion { get; set; }
        public DbSet<Categoria> Categorias { get; set; }
        public DbSet<Empresa> Empresas { get; set; }
        public DbSet<EntradaPresentacion> EntradasPresentaciones { get; set; }
        public DbSet<Factura> Facturas { get; set; }
        public DbSet<Grupo> Grupos { get; set; }
        public DbSet<Insumo> Insumos { get; set; }
        public DbSet<InsumoElaborado> InsumosElaborados { get; set; }
        public DbSet<Presentacion> Presentaciones { get; set; }
        public DbSet<ProductoPromocion> ProductoPromocion { get; set; }
        public DbSet<Producto> Productos { get; set; }
        public DbSet<Promocion> Promociones { get; set; }
        public DbSet<Proveedor> Proveedores { get; set; }
        public DbSet<Receta> Recetas { get; set; }
        public DbSet<Salida_almacen> Salidas_almacen { get; set; }
        public DbSet<Tipo_movimiento> Tipo_movimientos { get; set; }
        public DbSet<Unidad_Medida> Unidades_Medida { get; set; }
    }
}
