//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharkAdministrativo.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Data;
    using SDKCONTPAQi;
    
    public partial class EntradaPresentacion
    {
        public int id { get; set; }
        public int presentacion_id { get; set; }
        public int almacen_id { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Presentacion Presentacion { get; set; }

        /// <summary>
        /// Registra una entrada de almacén en Shark.
        /// </summary>
        /// <param name="entrada"></param>
        public void registrar(EntradaPresentacion entrada)
        {
            using (bdsharkEntities db = new bdsharkEntities())
            {
                db.Configuration.LazyLoadingEnabled = true;
                db.Presentaciones.Attach(entrada.Presentacion);
                db.Almacenes.Attach(entrada.Almacen);
                db.EntradasPresentaciones.Add(entrada);
                db.SaveChanges();
            }

        }
    }
}
