//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharkAdministrativo.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;

    public partial class Tipo_movimiento
    {
        public Tipo_movimiento()
        {
            this.Salida_almacen = new HashSet<Salida_almacen>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Salida_almacen> Salida_almacen { get; set; }

        public List<Tipo_movimiento> obtenerTodos()
        {
            List<Tipo_movimiento> movimientos = new List<Tipo_movimiento>();
            using (bdsharkEntities db = new bdsharkEntities())
            {
                db.Configuration.LazyLoadingEnabled = true;
                var Query = from movimiento in db.Tipo_movimientos select movimiento;
                foreach (var movimiento in Query)
                {
                    movimientos.Add(movimiento);
                }
            }
            return movimientos;
        }
    }
}
